URL_GEO_DEC = "https://yandex.ru/maps/org/donntu_korpus_4/1166354463/?ll=37.802884%2C47.993980&z=19.37"
URL_PROFKOM = "https://yandex.ru/maps/-/CCUVQJUyWB"
VK_IKNT = "https://vk.com/iknt_donntu"
INST_IKNT = "https://instagram.com/knt_donntu"
IST_IKNT = "http://fist.iknt.donntu.ru"
ISP_IKNT = "http://fisp.iknt.donntu.ru"
GRADES = "http://asu.donntu.ru"
PROFKOM_VK = "https://vk.com/profkomstud_donntu"